### PR TITLE
feat: upgrade bson to 0.4.x

### PR DESCRIPTION
**Pull request by AVVS**
this should be handy, as this one is as performant as c++ native version, but doesn't require one any longer

### CODE REVIEW

**Comment by AVVS** [comment]
@barshow I've seen some of these tests fail earlier on my own machine with old versions as well, but they are not consistent. Sometimes they pass, sometimes they dont, seems like there could be a race condition here?

**Comment by barshow** [comment]
Ive seen this guy: Exchange test it can declare a exchange with no callback
fail on travis with node 10 some, usually i just restart that one test and it will pass.  I have also spent quite a bit of time playing with it locally trying to break it with no success.  have you been able to get that one to fail locally?

**Comment by AVVS** [comment]
when I was playing with BSON (forgot to upgrade it in consumer/publisher and only updated in tests) the process was crashing a lot. It left a lot of stuff in local rabbitmq (queues, both direct and fanout) and other mess. When running tests again - they would never pass (many of them). After I've cleaned up rabbit - everything was green again. So I assume that there are some tests that require to be completed in a specific order and can cause all kind of trouble if something from a previous test hasn't completed/cleaned up - maybe its the same case with this one.

**Comment by barshow** [comment]
It doesn't shouldn't need a clean env to run.  But making sure the tests leave nothing behind is something I have wanted to do for a while.

**Pull request merged**
